name: tekartik_web_publish
description: Web publishing helpers
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  path: '>=1.8.0'
  process_run:
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart3a
    version: '>=0.6.2'
dev_dependencies:
  lints: '>=3.0.0'
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints

  test: '>=1.24.0'
