name: tekartik_flutter_build
description: Flutter build and deploy helpers
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  path: ">=1.9.0"
  process_run: ">=1.2.1+1"
  dev_build: ">=1.1.2"
  tekartik_common_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/common_build
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
    version: '>=0.6.2'
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
    version: '>=0.6.1'
  tekartik_web_publish:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/web_publish
dev_dependencies:
  test: ">=1.24.0"
resolution: workspace

