name: tekartik_flutter_build
description: Flutter build and deploy helpers
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  path: '>=1.7.0'
  process_run: '>=1.0.0+1'
  dev_build: '>=0.1.0'
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart3a
    version: '>=0.6.2'
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart3a
    version: '>=0.6.1'
  tekartik_web_publish:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/web_publish
dev_dependencies:
  test: '>=1.14.4'

dependency_overrides:
  tekartik_web_publish:
    path: ../web_publish
