name: tekartik_gcr_build
description: Google Cloud Run experiment
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.12.0

# Add regular dependencies here.
dependencies:
  path: ">=1.9.1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
  dev_build: ">=1.1.7+3"
  process_run: ">=1.2.1+1"
  tekartik_common_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/common_build

dev_dependencies:
  lints: ">=6.1.0"
  test: ">=1.31.0"
resolution: workspace
