name: tekartik_firebase_build
description: Firebase build and deploy helpers
version: 0.1.1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: ^1.7.0
  process_run:
  dev_test:
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart3a
    version: '>=0.6.2'
dev_dependencies:
  test: ^1.14.4
