name: tekartik_firebase_build
description: Firebase build and deploy helpers
version: 0.1.1
publish_to: none

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  path: ^1.7.0
  process_run:
  dev_test:
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart2_3
    version: '>=0.6.2'
dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
