name: tekartik_firebase_build
description: Firebase build and deploy helpers
version: 0.1.2
publish_to: none

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  path: '>=1.7.0'
  process_run:
  dev_build:
  tekartik_deploy:
    git:
      url: https://github.com/tekartik/deploy.dart
      ref: dart3a
    version: '>=0.6.2'
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart3a
    version: '>=0.6.1'
dev_dependencies:
  test: '>=1.14.4'
