name: tekartik_playstore_publish
description: A sample command-line application.
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.9.0

resolution: workspace
# Add regular dependencies here.
dependencies:
  path: ">=1.9.0"
  args: ">=2.6.0"
  googleapis: '>=12.0.0'
  googleapis_auth: '>=1.4.1'
  process_run: ">=1.2.1+1"
  tekartik_io_auth_utils:
    git:
      url: https://github.com/tekartik/io_auth_utils.dart
      ref: dart3a
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart3a
    version: '>=0.1.0'
dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
