name: tekartik_playstore_publish
description: A sample command-line application.
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.1.4

# Add regular dependencies here.
dependencies:
  path:
  args:
  googleapis:
  googleapis_auth:
  tekartik_io_auth_utils:
    git:
      url: https://github.com/tekartik/io_auth_utils.dart
      ref: dart3a
  tekartik_android_utils:
    git:
      url: https://github.com/tekartik/android_utils.dart
      ref: dart3a
    version: '>=0.1.0'
dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
