name: tekartik_firebase_build_menu_flutter
description: Build menu flutter
version: 0.3.5
publish_to: none

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  path: '>=1.6.0'
  dev_build: '>=0.16.5-6'
  process_run: '>=0.10.2'
  args: '>=2.4.2'
  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      ref: dart3a
      path: packages/firebase_build
    version: '>=0.1.0'
  tekartik_build_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/build_flutter
    version: '>=1.0.2'
  uuid: '>=3.0.0-0'

  tekartik_built_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      ref: dart3a
      path: packages/built_flutter
    version: '>=0.1.0'
  tekartik_app_args:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      ref: dart3a
      path: packages/app_args
    version: '>=0.1.0'

dev_dependencies:
  lints: '>=1.0.0'
  test: '>=1.16.0'

dependency_overrides:
  tekartik_firebase_build:
    path: ../firebase_build
executables:
  fbm: fbm
