name: tekartik_firebase_build_menu_flutter
description: Build menu flutter
version: 0.3.4
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  path: ">=1.9.0"
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  args: ">=2.6.0"
  tekartik_firebase_build:
    git:
      url: https://github.com/tekartik/app_build.dart
      path: packages/firebase_build
    version: '>=0.1.0'
  tekartik_build_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      path: packages/build_flutter
    version: '>=1.0.2'
  uuid: '>=3.0.0-0'
  tekartik_test_menu_io:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu_io
  tekartik_test_menu:
    git:
      url: https://github.com/tekartik/test_menu.dart
      path: test_menu
  tekartik_built_flutter:
    git:
      url: https://github.com/tekartik/build_flutter.dart
      path: packages/built_flutter
    version: '>=0.1.0'
  tekartik_app_args:
    git:
      url: https://github.com/tekartik/app_io_utils.dart
      path: packages/app_args
    version: '>=0.1.0'

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"

executables:
  fbm: fbm
resolution: workspace
