name: tekartik_common_build
description: Common build helper.
version: 1.0.0
publish_to: none;

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  dev_build: ">=1.1.2"
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
  fs_shim: ">=2.3.3+1"

dev_dependencies:
  lints: ">=5.0.0"
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      path: packages/lints
  test: '>=1.24.0'
resolution: workspace
