name: tekartik_appstore_publish
description: IOS appstore publish
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  process_run: ">=1.2.1+1"
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a

dev_dependencies:
  lints: ">=5.0.0"
  test: ">=1.24.0"
resolution: workspace
