name: tekartik_appstore_publish
description: IOS appstore publish
version: 0.1.1
publish_to: none

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  process_run: '>=0.14.1+3'

dev_dependencies:
  lints: '>=2.0.0'
  test: '>=1.21.0'
